

server:
  port: 9097
spring:
  ai:
    openai:
      api-key: ${API_KEY}
  application:
    name: questions-generator
  data:
    mongodb:
      uri: mongodb://localhost:27017/questionsdb
  profiles:
    active: dev
  config:
    import: configserver:http://localhost:9094
  cloud:
    function:
      definition: getQuizBinding

      web:
        path: "/functions"
    stream:
      defaultBinder: KafkaBinder
      binders:
        KafkaBinder:
          type: kafka
      kafka:
        binder:
          brokers:
            - localhost:9098

      bindings:
        getQuizBinding-in-0:
          destination: quiz-created
          group: ${spring.application.name}
        getQuizBinding-out-0:
          destination: acknowledge-quiz
          group: ${spring.application.name}






management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

resilience4j.circuitbreaker:
  instances:
    quizCB:
      registerHealthIndicator: true
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      minimum-number-of-calls: 10
      maxWaitDurationInHalfOpenState: 5000

