apiVersion: apps/v1
kind: Deployment
metadata:
  name: irctc-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: irctc-backend
  template:
    metadata:
      labels:
        app: irctc-backend
    spec:
      containers:
        - name: irctc-backend
          image: batchlcwd/irctc-backend:v1
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql:3306/irctcdb?useSSL=false&allowPublicKeyRetrieval=true"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "root1234"

---
apiVersion: v1
kind: Service
metadata:
  name: irctc-backend-service
spec:
  selector:
    app: irctc-backend
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30082
  type: NodePort
