spring:
  application:
    name: quiz-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/quizdb
  profiles:
    active: dev
  config:
    import: configserver:http://localhost:9094
  cloud:
    function:
      web:
        path: "/functions"
      definition: acknowledgeInformation
    stream:
      bindings:
        quizCreatedBinding-out-0:
          destination: quiz-created
          group: ${spring.application.name}
        acknowledgeInformation-in-0:
          destination: acknowledge-quiz
          group: ${spring.application.name}




  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10s


server:
  port: 9092

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

resilience4j.circuitbreaker:
  instances:
    quizCB:
      registerHealthIndicator: true
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      minimum-number-of-calls: 10
      maxWaitDurationInHalfOpenState: 5000

